[2025-01-24T09:03:15.267-0300] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-24T09:03:15.273-0300] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ReadPacTrat.readPacTrat scheduled__2020-03-18T01:10:00+00:00 [queued]>
[2025-01-24T09:03:15.276-0300] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ReadPacTrat.readPacTrat scheduled__2020-03-18T01:10:00+00:00 [queued]>
[2025-01-24T09:03:15.276-0300] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-01-24T09:03:15.291-0300] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): readPacTrat> on 2020-03-18 01:10:00+00:00
[2025-01-24T09:03:15.298-0300] {standard_task_runner.py:72} INFO - Started process 13389 to run task
[2025-01-24T09:03:15.300-0300] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'ReadPacTrat', 'readPacTrat', 'scheduled__2020-03-18T01:10:00+00:00', '--job-id', '164', '--raw', '--subdir', 'DAGS_FOLDER/DAGFiltroPacientesTratamento.py', '--cfg-path', '/tmp/tmpz4_bumru']
[2025-01-24T09:03:15.301-0300] {standard_task_runner.py:105} INFO - Job 164: Subtask readPacTrat
[2025-01-24T09:03:15.323-0300] {task_command.py:467} INFO - Running <TaskInstance: ReadPacTrat.readPacTrat scheduled__2020-03-18T01:10:00+00:00 [running]> on host lucas-Aspire-A514-54
[2025-01-24T09:03:15.445-0300] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='lucas' AIRFLOW_CTX_DAG_ID='ReadPacTrat' AIRFLOW_CTX_TASK_ID='readPacTrat' AIRFLOW_CTX_EXECUTION_DATE='2020-03-18T01:10:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2020-03-18T01:10:00+00:00'
[2025-01-24T09:03:15.446-0300] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-01-24T09:03:15.446-0300] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-01-24T09:03:15.446-0300] {logging_mixin.py:190} INFO - Current task name:readPacTrat state:running start_date:2025-01-24 12:03:15.273489+00:00
[2025-01-24T09:03:15.446-0300] {logging_mixin.py:190} INFO - Dag name:ReadPacTrat and current dag run status:running
[2025-01-24T09:03:15.446-0300] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-24T09:03:15.447-0300] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/lucas/airflow_env/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucas/airflow_env/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucas/airflow_env/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucas/airflow_env/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucas/airflow_env/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucas/airflow_env/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucas/airflow_env/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucas/airflow/dags/DAGFiltroPacientesTratamento.py", line 9, in read_excel
    df=pd.read_excel('/home/lucas/airflow/input/b1.CSV', header=[1,2], skipfooter=0)
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucas/airflow_env/lib/python3.12/site-packages/pandas/io/excel/_base.py", line 495, in read_excel
    io = ExcelFile(
         ^^^^^^^^^^
  File "/home/lucas/airflow_env/lib/python3.12/site-packages/pandas/io/excel/_base.py", line 1550, in __init__
    ext = inspect_excel_format(
          ^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucas/airflow_env/lib/python3.12/site-packages/pandas/io/excel/_base.py", line 1402, in inspect_excel_format
    with get_handle(
         ^^^^^^^^^^^
  File "/home/lucas/airflow_env/lib/python3.12/site-packages/pandas/io/common.py", line 882, in get_handle
    handle = open(handle, ioargs.mode)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/lucas/airflow/input/b1.CSV'
[2025-01-24T09:03:15.452-0300] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-01-24T09:03:15.452-0300] {logging_mixin.py:190} INFO - Task start:2025-01-24 12:03:15.273489+00:00 end:2025-01-24 12:03:15.452172+00:00 duration:0.178683
[2025-01-24T09:03:15.452-0300] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): readPacTrat> dag:<DAG: ReadPacTrat> dagrun:<DagRun ReadPacTrat @ 2020-03-18 01:10:00+00:00: scheduled__2020-03-18T01:10:00+00:00, state:running, queued_at: 2025-01-24 12:03:07.492811+00:00. externally triggered: False>
[2025-01-24T09:03:15.452-0300] {logging_mixin.py:190} INFO - Failure caused by [Errno 2] No such file or directory: '/home/lucas/airflow/input/b1.CSV'
[2025-01-24T09:03:15.452-0300] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=ReadPacTrat, task_id=readPacTrat, run_id=scheduled__2020-03-18T01:10:00+00:00, execution_date=20200318T011000, start_date=20250124T120315, end_date=20250124T120315
[2025-01-24T09:03:15.461-0300] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-24T09:03:15.462-0300] {standard_task_runner.py:124} ERROR - Failed to execute job 164 for task readPacTrat ([Errno 2] No such file or directory: '/home/lucas/airflow/input/b1.CSV'; 13389)
Traceback (most recent call last):
  File "/home/lucas/airflow_env/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucas/airflow_env/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucas/airflow_env/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/lucas/airflow_env/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucas/airflow_env/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucas/airflow_env/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/lucas/airflow_env/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucas/airflow_env/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/lucas/airflow_env/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/lucas/airflow_env/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucas/airflow_env/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucas/airflow_env/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucas/airflow_env/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucas/airflow_env/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucas/airflow_env/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucas/airflow_env/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucas/airflow_env/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucas/airflow_env/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucas/airflow/dags/DAGFiltroPacientesTratamento.py", line 9, in read_excel
    df=pd.read_excel('/home/lucas/airflow/input/b1.CSV', header=[1,2], skipfooter=0)
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucas/airflow_env/lib/python3.12/site-packages/pandas/io/excel/_base.py", line 495, in read_excel
    io = ExcelFile(
         ^^^^^^^^^^
  File "/home/lucas/airflow_env/lib/python3.12/site-packages/pandas/io/excel/_base.py", line 1550, in __init__
    ext = inspect_excel_format(
          ^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucas/airflow_env/lib/python3.12/site-packages/pandas/io/excel/_base.py", line 1402, in inspect_excel_format
    with get_handle(
         ^^^^^^^^^^^
  File "/home/lucas/airflow_env/lib/python3.12/site-packages/pandas/io/common.py", line 882, in get_handle
    handle = open(handle, ioargs.mode)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/lucas/airflow/input/b1.CSV'
[2025-01-24T09:03:15.472-0300] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-01-24T09:03:15.483-0300] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-24T09:03:15.484-0300] {local_task_job_runner.py:245} INFO - ::endgroup::
