[2025-01-24T11:20:11.181-0300] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-24T11:20:11.187-0300] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: MergePacTratAgeng.coping scheduled__2020-03-18T00:30:00+00:00 [queued]>
[2025-01-24T11:20:11.190-0300] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: MergePacTratAgeng.coping scheduled__2020-03-18T00:30:00+00:00 [queued]>
[2025-01-24T11:20:11.190-0300] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-01-24T11:20:11.200-0300] {taskinstance.py:2889} INFO - Executing <Task(BashOperator): coping> on 2020-03-18 00:30:00+00:00
[2025-01-24T11:20:11.203-0300] {standard_task_runner.py:72} INFO - Started process 60861 to run task
[2025-01-24T11:20:11.205-0300] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'MergePacTratAgeng', 'coping', 'scheduled__2020-03-18T00:30:00+00:00', '--job-id', '2246', '--raw', '--subdir', 'DAGS_FOLDER/DAGAgendXPac.py', '--cfg-path', '/tmp/tmpz7b2_u8z']
[2025-01-24T11:20:11.206-0300] {standard_task_runner.py:105} INFO - Job 2246: Subtask coping
[2025-01-24T11:20:11.227-0300] {task_command.py:467} INFO - Running <TaskInstance: MergePacTratAgeng.coping scheduled__2020-03-18T00:30:00+00:00 [running]> on host lucas-Aspire-A514-54
[2025-01-24T11:20:11.260-0300] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='lucas' AIRFLOW_CTX_DAG_ID='MergePacTratAgeng' AIRFLOW_CTX_TASK_ID='coping' AIRFLOW_CTX_EXECUTION_DATE='2020-03-18T00:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2020-03-18T00:30:00+00:00'
[2025-01-24T11:20:11.261-0300] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-24T11:20:11.269-0300] {subprocess.py:78} INFO - Tmp dir root location: /tmp
[2025-01-24T11:20:11.270-0300] {subprocess.py:88} INFO - Running command: ['/usr/bin/bash', '-c', 'cp -f PAC_TRAT_AGEND.csv PAC_TRAT_FILTER.csv ./input/.']
[2025-01-24T11:20:11.277-0300] {subprocess.py:99} INFO - Output:
[2025-01-24T11:20:11.278-0300] {subprocess.py:106} INFO - cp: alvo './input/.': Arquivo ou diret√≥rio inexistente
[2025-01-24T11:20:11.278-0300] {subprocess.py:110} INFO - Command exited with return code 1
[2025-01-24T11:20:11.282-0300] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/lucas/airflow_env/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucas/airflow_env/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucas/airflow_env/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucas/airflow_env/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucas/airflow_env/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-01-24T11:20:11.285-0300] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=MergePacTratAgeng, task_id=coping, run_id=scheduled__2020-03-18T00:30:00+00:00, execution_date=20200318T003000, start_date=20250124T142011, end_date=20250124T142011
[2025-01-24T11:20:11.294-0300] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-24T11:20:11.295-0300] {standard_task_runner.py:124} ERROR - Failed to execute job 2246 for task coping (Bash command failed. The command returned a non-zero exit code 1.; 60861)
Traceback (most recent call last):
  File "/home/lucas/airflow_env/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucas/airflow_env/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucas/airflow_env/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/lucas/airflow_env/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucas/airflow_env/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucas/airflow_env/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/lucas/airflow_env/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucas/airflow_env/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/lucas/airflow_env/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/lucas/airflow_env/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucas/airflow_env/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucas/airflow_env/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucas/airflow_env/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucas/airflow_env/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucas/airflow_env/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucas/airflow_env/lib/python3.12/site-packages/airflow/operators/bash.py", line 276, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-01-24T11:20:11.337-0300] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-01-24T11:20:11.358-0300] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-24T11:20:11.359-0300] {local_task_job_runner.py:245} INFO - ::endgroup::
