[2025-01-13T22:12:44.450-0300] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-13T22:12:44.456-0300] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: MyCSVDAG.convertCSVtoJson scheduled__2020-03-18T01:15:00+00:00 [queued]>
[2025-01-13T22:12:44.461-0300] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: MyCSVDAG.convertCSVtoJson scheduled__2020-03-18T01:15:00+00:00 [queued]>
[2025-01-13T22:12:44.461-0300] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-01-13T22:12:44.470-0300] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): convertCSVtoJson> on 2020-03-18 01:15:00+00:00
[2025-01-13T22:12:44.473-0300] {standard_task_runner.py:72} INFO - Started process 44190 to run task
[2025-01-13T22:12:44.475-0300] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'MyCSVDAG', 'convertCSVtoJson', 'scheduled__2020-03-18T01:15:00+00:00', '--job-id', '35', '--raw', '--subdir', 'DAGS_FOLDER/DAGCsvToJson.py', '--cfg-path', '/tmp/tmpke303ab1']
[2025-01-13T22:12:44.476-0300] {standard_task_runner.py:105} INFO - Job 35: Subtask convertCSVtoJson
[2025-01-13T22:12:44.501-0300] {task_command.py:467} INFO - Running <TaskInstance: MyCSVDAG.convertCSVtoJson scheduled__2020-03-18T01:15:00+00:00 [running]> on host lucas-Aspire-A514-54
[2025-01-13T22:12:44.620-0300] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='paulcrickard' AIRFLOW_CTX_DAG_ID='MyCSVDAG' AIRFLOW_CTX_TASK_ID='convertCSVtoJson' AIRFLOW_CTX_EXECUTION_DATE='2020-03-18T01:15:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2020-03-18T01:15:00+00:00'
[2025-01-13T22:12:44.620-0300] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-01-13T22:12:44.621-0300] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-01-13T22:12:44.621-0300] {logging_mixin.py:190} INFO - Current task name:convertCSVtoJson state:running start_date:2025-01-14 01:12:44.456885+00:00
[2025-01-13T22:12:44.621-0300] {logging_mixin.py:190} INFO - Dag name:MyCSVDAG and current dag run status:running
[2025-01-13T22:12:44.621-0300] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-13T22:12:44.621-0300] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/lucas/airflow_env/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucas/airflow_env/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucas/airflow_env/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucas/airflow_env/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucas/airflow_env/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucas/airflow_env/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucas/airflow_env/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucas/airflow/dags/DAGCsvToJson.py", line 9, in CSVToJson
    df=pd.read_CSV('/home/paulcrickard/data.CSV')
       ^^^^^^^^^^^
AttributeError: module 'pandas' has no attribute 'read_CSV'. Did you mean: 'read_csv'?
[2025-01-13T22:12:44.626-0300] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-01-13T22:12:44.626-0300] {logging_mixin.py:190} INFO - Task start:2025-01-14 01:12:44.456885+00:00 end:2025-01-14 01:12:44.626134+00:00 duration:0.169249
[2025-01-13T22:12:44.627-0300] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): convertCSVtoJson> dag:<DAG: MyCSVDAG> dagrun:<DagRun MyCSVDAG @ 2020-03-18 01:15:00+00:00: scheduled__2020-03-18T01:15:00+00:00, state:running, queued_at: 2025-01-14 01:12:38.757909+00:00. externally triggered: False>
[2025-01-13T22:12:44.627-0300] {logging_mixin.py:190} INFO - Failure caused by module 'pandas' has no attribute 'read_CSV'
[2025-01-13T22:12:44.627-0300] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=MyCSVDAG, task_id=convertCSVtoJson, run_id=scheduled__2020-03-18T01:15:00+00:00, execution_date=20200318T011500, start_date=20250114T011244, end_date=20250114T011244
[2025-01-13T22:12:44.637-0300] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-13T22:12:44.638-0300] {standard_task_runner.py:124} ERROR - Failed to execute job 35 for task convertCSVtoJson (module 'pandas' has no attribute 'read_CSV'; 44190)
Traceback (most recent call last):
  File "/home/lucas/airflow_env/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucas/airflow_env/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucas/airflow_env/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/lucas/airflow_env/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucas/airflow_env/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucas/airflow_env/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/lucas/airflow_env/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucas/airflow_env/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/lucas/airflow_env/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/lucas/airflow_env/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucas/airflow_env/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucas/airflow_env/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucas/airflow_env/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucas/airflow_env/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucas/airflow_env/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucas/airflow_env/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucas/airflow_env/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucas/airflow_env/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lucas/airflow/dags/DAGCsvToJson.py", line 9, in CSVToJson
    df=pd.read_CSV('/home/paulcrickard/data.CSV')
       ^^^^^^^^^^^
AttributeError: module 'pandas' has no attribute 'read_CSV'. Did you mean: 'read_csv'?
[2025-01-13T22:12:44.647-0300] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-01-13T22:12:44.656-0300] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-13T22:12:44.656-0300] {local_task_job_runner.py:245} INFO - ::endgroup::
