[2025-01-26T22:30:54.137-0300] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-26T22:30:54.148-0300] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: InsertIntoElastic.inject_data_into_es scheduled__2022-11-27T00:00:00+00:00 [queued]>
[2025-01-26T22:30:54.152-0300] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: InsertIntoElastic.inject_data_into_es scheduled__2022-11-27T00:00:00+00:00 [queued]>
[2025-01-26T22:30:54.152-0300] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-01-26T22:30:54.167-0300] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): inject_data_into_es> on 2022-11-27 00:00:00+00:00
[2025-01-26T22:30:54.171-0300] {standard_task_runner.py:72} INFO - Started process 114529 to run task
[2025-01-26T22:30:54.173-0300] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'InsertIntoElastic', 'inject_data_into_es', 'scheduled__2022-11-27T00:00:00+00:00', '--job-id', '5800', '--raw', '--subdir', 'DAGS_FOLDER/DAGInjectElastic.py', '--cfg-path', '/tmp/tmp8xu2vrml']
[2025-01-26T22:30:54.176-0300] {standard_task_runner.py:105} INFO - Job 5800: Subtask inject_data_into_es
[2025-01-26T22:30:54.208-0300] {task_command.py:467} INFO - Running <TaskInstance: InsertIntoElastic.inject_data_into_es scheduled__2022-11-27T00:00:00+00:00 [running]> on host lucas-Aspire-A514-54
[2025-01-26T22:30:54.270-0300] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='lucas' AIRFLOW_CTX_DAG_ID='InsertIntoElastic' AIRFLOW_CTX_TASK_ID='inject_data_into_es' AIRFLOW_CTX_EXECUTION_DATE='2022-11-27T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2022-11-27T00:00:00+00:00'
[2025-01-26T22:30:54.271-0300] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-26T22:30:54.649-0300] {_transport.py:349} INFO - PUT http://localhost:9200/_bulk [status:200 duration:0.132s]
[2025-01-26T22:30:54.662-0300] {DAGInjectElastic.py:93} ERROR - Error uploading data to Elasticsearch: 500 document(s) failed to index.
[2025-01-26T22:30:54.669-0300] {python.py:240} INFO - Done. Returned value was: False
[2025-01-26T22:30:54.683-0300] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-26T22:30:54.683-0300] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=InsertIntoElastic, task_id=inject_data_into_es, run_id=scheduled__2022-11-27T00:00:00+00:00, execution_date=20221127T000000, start_date=20250127T013054, end_date=20250127T013054
[2025-01-26T22:30:54.707-0300] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-26T22:30:54.714-0300] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-26T22:30:54.715-0300] {local_task_job_runner.py:245} INFO - ::endgroup::
